### PR TITLE
Rebuild version 2.4.4 with Python 3.9

### PR DESCRIPTION
**Pull request by corydolphin**
This is a spike to try to get gdal to build with Python 3.9. 🤞 

Checklist
* [X ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by corydolphin** [comment]
@conda-forge-admin, please rerender

**Comment by corydolphin** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
```
2021-07-17T01:55:40.6863404Z pdfdataset.cpp: In static member function 'static GDALDataset* PDFDataset::Open(GDALOpenInfo*)':
2021-07-17T01:55:40.6865228Z pdfdataset.cpp:4072:22: error: invalid conversion from 'void (*)(void*, ErrorCategory, Goffset, const char*)' {aka 'void (*)(void*, ErrorCategory, long long int, const char*)'} to 'ErrorCallback' {aka 'void (*)(ErrorCategory, long long int, const char*)'} [-fpermissive]
2021-07-17T01:55:40.6866104Z  4072 |     setErrorCallback(PDFDatasetErrorFunction, nullptr);
2021-07-17T01:55:40.6866565Z       |                      ^~~~~~~~~~~~~~~~~~~~~~~
2021-07-17T01:55:40.6867100Z       |                      |
2021-07-17T01:55:40.6867624Z       |                      void (*)(void*, ErrorCategory, Goffset, const char*) {aka void (*)(void*, ErrorCategory, long long int, const char*)}
2021-07-17T01:55:40.6869016Z pdfdataset.cpp:4072:54: error: too many arguments to function 'void setErrorCallback(ErrorCallback)'
2021-07-17T01:55:40.6870393Z  4072 |     setErrorCallback(PDFDatasetErrorFunction, nullptr);
2021-07-17T01:55:40.6870917Z       |                                                      ^
2021-07-17T01:55:40.6872333Z In file included from /home/conda/feedstock_root/build_artifacts/gdal-split_1626484592014/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/poppler/Object.h:45,
2021-07-17T01:55:40.6873216Z                  from pdfsdk_headers.h:64,
2021-07-17T01:55:40.6873673Z                  from gdal_pdf.h:53,
2021-07-17T01:55:40.6874103Z                  from pdfdataset.cpp:36:
2021-07-17T01:55:40.6875257Z /home/conda/feedstock_root/build_artifacts/gdal-split_1626484592014/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/poppler/Error.h:54:13: note: declared here
2021-07-17T01:55:40.6876116Z    54 | extern void setErrorCallback(ErrorCallback cbk);
2021-07-17T01:55:40.6876542Z       |             ^~~~~~~~~~~~~~~~
2021-07-17T01:55:41.1238970Z make[2]: *** [../o/pdfdataset.lo] Error 1
2021-07-17T01:55:41.1240817Z make[1]: *** [pdf-install-obj] Error 2
2021-07-17T01:55:41.1251929Z make: make[2]: Leaving directory `$SRC_DIR/frmts/pdf'
2021-07-17T01:55:41.1266248Z make[1]: Leaving directory `$SRC_DIR/frmts'
2021-07-17T01:55:41.1266970Z *** [frmts-target] Error 2
2021-07-17T01:55:41.1267427Z make: *** Waiting for unfinished jobs....
```

Is this an issue with the compiler, or newer libs with old GDAL?

**Comment by corydolphin** [comment]
> ```
> 2021-07-17T01:55:40.6863404Z pdfdataset.cpp: In static member function 'static GDALDataset* PDFDataset::Open(GDALOpenInfo*)':
> 2021-07-17T01:55:40.6865228Z pdfdataset.cpp:4072:22: error: invalid conversion from 'void (*)(void*, ErrorCategory, Goffset, const char*)' {aka 'void (*)(void*, ErrorCategory, long long int, const char*)'} to 'ErrorCallback' {aka 'void (*)(ErrorCategory, long long int, const char*)'} [-fpermissive]
> 2021-07-17T01:55:40.6866104Z  4072 |     setErrorCallback(PDFDatasetErrorFunction, nullptr);
> 2021-07-17T01:55:40.6866565Z       |                      ^~~~~~~~~~~~~~~~~~~~~~~
> 2021-07-17T01:55:40.6867100Z       |                      |
> 2021-07-17T01:55:40.6867624Z       |                      void (*)(void*, ErrorCategory, Goffset, const char*) {aka void (*)(void*, ErrorCategory, long long int, const char*)}
> 2021-07-17T01:55:40.6869016Z pdfdataset.cpp:4072:54: error: too many arguments to function 'void setErrorCallback(ErrorCallback)'
> 2021-07-17T01:55:40.6870393Z  4072 |     setErrorCallback(PDFDatasetErrorFunction, nullptr);
> 2021-07-17T01:55:40.6870917Z       |                                                      ^
> 2021-07-17T01:55:40.6872333Z In file included from /home/conda/feedstock_root/build_artifacts/gdal-split_1626484592014/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/poppler/Object.h:45,
> 2021-07-17T01:55:40.6873216Z                  from pdfsdk_headers.h:64,
> 2021-07-17T01:55:40.6873673Z                  from gdal_pdf.h:53,
> 2021-07-17T01:55:40.6874103Z                  from pdfdataset.cpp:36:
> 2021-07-17T01:55:40.6875257Z /home/conda/feedstock_root/build_artifacts/gdal-split_1626484592014/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/poppler/Error.h:54:13: note: declared here
> 2021-07-17T01:55:40.6876116Z    54 | extern void setErrorCallback(ErrorCallback cbk);
> 2021-07-17T01:55:40.6876542Z       |             ^~~~~~~~~~~~~~~~
> 2021-07-17T01:55:41.1238970Z make[2]: *** [../o/pdfdataset.lo] Error 1
> 2021-07-17T01:55:41.1240817Z make[1]: *** [pdf-install-obj] Error 2
> 2021-07-17T01:55:41.1251929Z make: make[2]: Leaving directory `$SRC_DIR/frmts/pdf'
> 2021-07-17T01:55:41.1266248Z make[1]: Leaving directory `$SRC_DIR/frmts'
> 2021-07-17T01:55:41.1266970Z *** [frmts-target] Error 2
> 2021-07-17T01:55:41.1267427Z make: *** Waiting for unfinished jobs....
> ```
> 
> Is this an issue with the compiler, or newer libs with old GDAL?

I'm thinking it is poppler. I'll try pinning.

**Comment by corydolphin** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@corydolphin I think if you are going to make this work you need to patch `gdal` to work with the new `poppler`. Pinning things to older versions is usually unsuccessful as there are conflicts with the other dependencies...

**Comment by xylar** [comment]
@corydolphin, are you still interested in trying do to this?  It seems like maybe this attempt wasn't successful and could be closed?

**Comment by corydolphin** [comment]
> @corydolphin, are you still interested in trying do to this? It seems like maybe this attempt wasn't successful and could be closed?

Closed! I gave up trying to figure my way out of the dependency quagmire for now. Sorry for the noise/staleness
