### ISSUE TITLE
Failing to compile on Windows with latest hdf5 (1.8.16)

### ISSUE THREAD

**Issue by gillins** [conda-forge/gdal-feedstock#25]
I get the errors below with conda-forge's hdf5. I've logged it here as the symbols are in fact exported in the lib/dll so likely to be a weird include problem inside GDAL.

```
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_DOUBLE_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPEBDAEAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_DOUBLE_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_FLOAT_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPEBDAEAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_FLOAT_g
hdf5imagedataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_FLOAT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_INT_g referenced in function "bool __cdecl GH5_FetchAttribute(int,char const *,double &,bool)" (?GH5_FetchAttribute@@YA_NHPEBDAEAN_N@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_INT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_ULLONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_ULLONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_LLONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_LLONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_ULONG
_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_ULONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_LONG_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_LONG_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_UINT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_UINT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_USHORT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_USHORT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_SHORT_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_SHORT_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_UCHAR_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_UCHAR_g
gh5_convenience.obj : error LNK2019: unresolved external symbol H5T_NATIVE_SCHAR
_g referenced in function "enum GDALDataType __cdecl GH5_GetDataType(int)" (?GH5_GetDataType@@YA?AW4GDALDataType@@H@Z)
hdf5dataset.obj : error LNK2001: unresolved external symbol H5T_NATIVE_SCHAR_g
gdal200.dll : fatal error LNK1120: 12 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\Bin\amd64\link.EXE"' : return code '0x460'
```

**Comment by ocefpaf** [comment]
I believe that we need to copile our `libnetcdf` first. We must pin hdf5 to 1.8.15.1 until then.

**Comment by groutr** [comment]
hmm...Not the only one getting this error I see. :)

**Comment by jakirkham** [comment]
We should be pinning to HDF5 1.8.15.1, which is what this PR ( https://github.com/conda-forge/gdal-feedstock/pull/27 ) did. So can this now be closed or is this still an issue?

**Comment by gillins** [comment]
Yep let's close it and see what happens when netcdf is upgraded.

**Comment by groutr** [comment]
This issue can be resolved with the following patch (credit to Christoph Gohlke)
```
diff --git frmts/hdf5/makefile.vc frmts/hdf5/makefile.vc
index e2e695d..02f006f 100644
--- frmts/hdf5/makefile.vc
+++ frmts/hdf5/makefile.vc
@@ -7,7 +7,7 @@ OBJ		=	hdf5dataset.obj  hdf5imagedataset.obj \
 
 PLUGIN_DLL 	=	gdal_HDF5.dll
 
-EXTRAFLAGS 	= 	-I$(HDF5_DIR)\include -DWIN32 -D_HDF5USEDLL_ 
+EXTRAFLAGS 	= 	-I$(HDF5_DIR)\include -DWIN32 -DH5_BUILT_AS_DYNAMIC_LIB
 
 !IF "$(HDF5_PLUGIN)" == "YES"
 EXTRAFLAGS = $(EXTRAFLAGS) -DHDF5_PLUGIN
```

**Comment by gillins** [comment]
Thanks @groutr! Same thing that tripped up kealib.
@ocefpaf - is netcdf still stuck with the older hdf? I suppose we need to update them both at the same time.

**Comment by ocefpaf** [comment]
> @ocefpaf - is netcdf still stuck with the older hdf? I suppose we need to update them both at the same time.

It is :unamused: 

The bottle neck is the `curl` [recipe](https://github.com/conda-forge/staged-recipes/pull/378).

**Comment by jakirkham** [comment]
Basically if we can get some Perl people to help us either package what we need or help us do some sort of hacky workaround that would be great. Then `curl` can move forward.

**Comment by gillins** [comment]
Seems this is expected with GDAL: https://trac.osgeo.org/gdal/wiki/HDF#BuildingonWindowswithMSVC

I'm not sure why it worked with the older HDF5, but the supplied makefile.vc seems set up for static linking, and you have to edit it to work for dynamic.
